[project]
name = "new-code-compiler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiofiles>=25.1.0",
    "fastapi[standard]>=0.120.0",
    "pydantic>=2.0.0",
    "redis>=4.0.0",
    "uvicorn[standard]>=0.38.0",
]
