version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      - QUEUE_URL=redis://redis:6379/0
    depends_on:
      - redis

  worker-python:
    build:
      context: .
      dockerfile: Dockerfile.python
    environment:
      - QUEUE_URL=redis://redis:6379/0
      - LANGUAGE=python
      - TMPDIR=/workspace/tmp
      - HOST_TMP_PATH=/home/aditya/my-work/De-Code/new-code-compiler/tmp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tmp:/workspace/tmp:rw

  worker-java:
    build:
      context: .
      dockerfile: Dockerfile.java
    environment:
      - QUEUE_URL=redis://redis:6379/0
      - LANGUAGE=java
      - TMPDIR=/workspace/tmp
      - HOST_TMP_PATH=/home/aditya/my-work/De-Code/new-code-compiler/tmp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tmp:/workspace/tmp:rw

  worker-cpp:
    build:
      context: .
      dockerfile: Dockerfile.cpp
    environment:
      - QUEUE_URL=redis://redis:6379/0
      - LANGUAGE=cpp
      - TMPDIR=/workspace/tmp
      - HOST_TMP_PATH=/home/aditya/my-work/De-Code/new-code-compiler/tmp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./tmp:/workspace/tmp:rw

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    command: ["redis-server", "--save", ""]

networks:
  default:
    name: code-compiler-network